USE Jogoteca;

CREATE DATABASE Jogoteca;


CREATE TABLE USUARIO(
    ID_USER INT PRIMARY KEY AUTO_INCREMENT, 
    USUARIO VARCHAR(110),
    SENHA VARCHAR(32)
);

CREATE TABLE JOGOS(
    ID_JOGO INT PRIMARY KEY AUTO_INCREMENT, 
    JOGO VARCHAR(130),
    CATEGORIA VARCHAR(130),
    CONSOLE VARCHAR(130),
    ID_USER INT,
    FOREIGN KEY(ID_USER) 
    REFERENCES USUARIO (ID_USER)
);
